### ISSUE TITLE
Failed to build basement-0.0.11.

### ISSUE THREAD

**Issue by adamneilson** [alessandrokonrad/Pi-Pool#1]
Thanks Alessandro, so near, yet so far...

I followed your steps 1-5 without any issue and can run ghc and cabal:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.2.0 of the Cabal library 
```

The problem for me was in step 6 with the `cabal build all`

```
Failed to build basement-0.0.11.
Build log (
/home/adam/.cabal/logs/ghc-8.6.5/basement-0.0.11-e48818d45b0edc0d0fdd2986734845bcef732ae70ea67ff9cb3825d85b9163fe.log
):
Configuring library for basement-0.0.11..
Preprocessing library for basement-0.0.11..
hsc2hs: dist/build/Basement/Terminal/Size_hsc_make: runProcess: runInteractiveProcess: exec: permission denied (Permission denied)
cabal: Failed to build basement-0.0.11 (which is required by
cardano-sl-x509-3.0.0, exe:chairman from cardano-node-1.14.0 and others). See
the build log above for details.
```

Have you come across this problem before? Is it anything to do with the recent upgrade to the node from cardano-node-1.13.0 to cardano-node-1.14.0?

System versions:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by alessandrokonrad** [comment]
Hey, maybe you can try this. There is a new node version 1.14.1:
```
git fetch --all --tags
git checkout tags/1.14.1
cabal update
echo -e "package cardano-crypto-praos\n  flags: -external-libsodium-vrf" > cabal.project.local​​
cabal install cardano-node cardano-cli​
cabal build all
```
But I think you problem isn't Pi related because you already have ghc and cabal working. It has more to do with node itself. I know that node version 1.13.0 was really stable and had no install issues. You can try to install that if you want to really make sure the problem has nothing to do with the Pi.

Let me know if 1.14.1 works with the steps above. I will update the guide then.

**Comment by adamneilson** [comment]
I'll give it a shot shortly and let you know how it goes.

**Comment by adamneilson** [comment]
I tried numerous variations on the above (even started again from scratch) and nothing gets past the error above as the existing user. 

So I started from scratch as root and it looks like it's working. It's been building for the last couple of hours but looking like it's happy.

That being said, it's not great that I need to do this as root. It's late on my side of the planet so I may try this again tomorrow with modified ownership of gch. I'll also try checking out tag `1.13.0` too to see if that works on the default user. 

One additional note on your comment above, I didn't understand the  `cabal install cardano-node cardano-cli​` step. It wasn't in the main readme and it fails:

```
$ cabal install cardano-node cardano-cli​
cabal: Unrecognised target 'cardano-cli​'.
Expected a meta-target 'all' or component kind filter or component name or
package name or package directory or package .cabal file or component name or
module name or file, rather than 'cardano-cli​'.
```

**Comment by alessandrokonrad** [comment]
That's strange. What parts do you do as root? 

I saw it in a couple tutorials, where they used <code>cabal install cardano-node cardano-cli</code>, before they do <code>cabal build all </code>. I thought it could work for you, but I really don't know why they do this step. It was also in one of the IOHK Tutorials.
