### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by mmudado** [alessandrokonrad/Pi-Pool#2]
After running a relay for a while in a Pi 4 / 4Gb RAM with a pi-fan,  I'm getting a core dumped and cardano-node crashes. Any ideas why?

**Comment by alessandrokonrad** [comment]
How many peers do you have connected to it?

**Comment by mmudado** [comment]
> How many peers do you have connected to it?

Around 20

**Comment by alessandrokonrad** [comment]
That could be the problem. I think it's not really a problem with the Pi, but rather with the node. Maybe the Pi is a little bit more sensitive to it. I would recommend having a max of 12-15 peers.

**Comment by mmudado** [comment]
> That could be the problem. I think it's not really a problem with the Pi, but rather with the node. Maybe the Pi is a little bit more sensitive to it. I would recommend having a max of 12-15 peers.

Will give it a try, thanks! I'll let you know the results, cheers!

**Comment by mmudado** [comment]
Running smoothly now for around 5 days uptime :+1: 

What I did: lowered peers to 13. Closed the "glances" software I was using to monitor temperatures.
I will try to raise peers now and see what happens. Thanks!
