### ISSUE TITLE
installing on a mac first

### ISSUE THREAD

**Issue by jasonsutter87** [alessandrokonrad/Pi-Pool#3]
Hey Alessandro,

I follow your directions on my Pi4 8gb and everything went perfect until my node was trying to sync and it keep crashing. 

im trying currently to set up the node now on my macbook that is running Linux
```
OS: ubuntu 20.04 LTS
kernal: 5.4.0-42-generic
Architecture x86-64
```

Im having trouble on step 4 at this point.  
Do i need to compile different binary files for my machine since its not running an ARM64?

```
4. Get Cabal 3.2 and remove Cabal 2.4:
wget https://github.com/alessandrokonrad/Pi-Pool/raw/master/aarch64/cabal3.2/cabal
chmod +x cabal
mkdir -p ~/.local/bin
mv cabal ~/.local/bin
sudo rm /usr/bin/cabal
```

**Comment by alessandrokonrad** [comment]
Hey, yes exactly. You can actually just follow the official guide to set up a node on Mac, because Mac is x86. You need cabal and ghc for x86.

**Comment by jasonsutter87** [comment]
you rock, thanks for your guide!
