### ISSUE TITLE
Can anyone point me to instructions after getting Pi-Pool booted?

### ISSUE THREAD

**Issue by jtmoderate876** [alessandrokonrad/Pi-Pool#5]
Firstly, Thank you @alessandrokonrad for creating Pi-Pool.

Can you or anyone else tell me the steps to go through once pi-pool is booted and running?
Things like:
Next change the password for the ada user 
Next change the password for admin user in Grafana
Next do:
 sudo apt-get update && sudo apt-get upgrade

**NOW...
How to update the cardano node software?**

**Comment by alessandrokonrad** [comment]
Hey, so updating is currently a thing that needs to be done manually. The most recent version is 1.24.2 and it is important to use that one.

https://github.com/input-output-hk/cardano-node This is the official repository where you see under releases what the latest version is. I would recommend you joining this <a href="https://t.me/joinchat/FeKTCBu-pn5OUZUz4joF2w">Telegram Group</a>. You can find there the latest cardano node binaries for raspberry pis without the need to build it first.
Also in my guide I mention in the very top of "Getting started" to update to 1.24.2 and there is a download link.

In the Zip file you will find two files: cardano-node and cardano-cli. These two files you have to replace with the old ones on your raspberry pi. You find them under the directory <code>~/.local/bin</code>

**Comment by jtmoderate876** [comment]
Thanks for the help. I will give it a try.
